services:
  relaymon:
    build:
      context: ../../..
      dockerfile: ./apps/relaymon/.docker/Dockerfile.clearnet
      no_cache: true
    container_name: relaymon
    restart: unless-stopped
    volumes:
      - ../data:/opt/data
      - ../.docker.env:/app/.env
      - ../.docker.env:/app/nostr-watch/apps/relaymon/.env
      - ../config.docker.yaml:/opt/config.yaml
      - ../data/relays.db:/opt/relays.db
    environment:
      - RELAYMON_CONFIG_PATH=/opt/config.yaml
      - RELAYMON_DB_PATH=/opt/relays.db
      - RELAYMON_SKIP_PID_CHECK=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
