services:
  relaymon:
<<<<<<< Updated upstream
    image: nostrwatch/relaymon:basic
=======
    image: nostrwatch/relaymon:clearnet
>>>>>>> Stashed changes
    container_name: relaymon
    restart: unless-stopped
    volumes:
      - ../data:/opt/data
      - ../.docker.env:/app/.env
      - ../.docker.env:/app/nostr-watch/apps/relaymon/.env
      - ../config.docker.yaml:/opt/config.yaml
      - ../data/relays.db:/opt/relays.db
    extra_hosts:
      - "host.docker.internal:host-gateway"
