FROM node:14-alpine as build

WORKDIR /app

COPY . /app/

RUN yarn && yarn build:quick

RUN yarn global add yaml-convert

RUN yaml-convert relays.yaml > dist/relays.json

FROM nginx:stable-alpine as nginx-nostr-relay-registry

COPY ./nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/public /app
COPY --from=build /app/dist /app
