packages:
    - "apps/*"
    - "demos/*"
    - "internal/*"
    - "internal/publisher/adapters/**/*"
    - "libraries/*"
    - "libraries/nocap/adapters/**/*"
    - "libraries/kit/adapters/**/*"
    - "libraries/route66/adapters/cache/**/*"
    - "libraries/route66/adapters/websocket/**/*"
    - "libraries/adapters/**/*"
    - "libraries/validators/**/*"
    - "libraries/schemata/*"
    - '!apps/nocapd'
    - '!libraries/nocap-route66'