version: "3"
services:
  nocapd:
    container_name: nocapd
    restart: unless-stopped
    image: nocapd
    tty: true
    build:     
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 0
      dockerfile: Dockerfile
    volumes:
      - /Users/sandwich/Develop/nostr-watch/.lmdb:/app/.lmdb:rw
      - ./.env.docker:/app/.env:ro
      - ./config.yaml:/app/config.yaml:ro
    environment:
      DOCKER: 'yes'
    env_file: .env.docker
    # depends_on: 
    #   - cache
    networks:
      - nocapdnet
  # cache:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   volumes: 
  #     - ./.redis:/.data:rw
  #   env_file: .env.docker
  #   command: redis-server
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   networks:
  #     - nocapdnet

volumes: 
  lmdb:
    driver: local
  # cache: 
  #   driver: local

networks:
  nocapdnet:
    driver: bridge
