base {
    log_debug = on;
    log_info = on;
    log = stderr;
    daemon = off;
    redirector = iptables;
}

redsocks {
    local_ip = 0.0.0.0;
    local_port = 12347;
    
    ip = 127.0.0.1;
    port = 12346;
    
    type = socks5;

    connect_timeout = 10;
    timeout = 300;
}

redudp {
    local_ip = 127.0.0.1;
    local_port = 10053;
    
    ip = 127.0.0.1;
    port = 12345;
    
    dest_ip = 8.8.8.8;
    dest_port = 53;
    
    udp_timeout = 30;
    udp_timeout_stream = 180;1
} 