name: Deploy GUI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install deps
        run: yarn install

      - name: Run alpha deploy
        run: ./scripts/deploy/gui.sh

      - name: Get package version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' ./apps/gui/package.json)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Prepare Directories
        env:
          HOST_IP: ${{ secrets.HOST_IP }}
          HOST_USER: ${{ secrets.HOST_USER }}
        run: |
          VERSION=${{ env.VERSION }}
          echo "Deploying version $VERSION"
          ssh -i ${{ secrets.SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }} << EOF
          set -e
          mkdir -p /var/www/html/${VERSION}
          rm -rf /var/www/html/latest
          ln -s /var/www/html/${VERSION} /var/www/html/latest
          EOF

      - name: Upload Build
        env:
          HOST_IP: ${{ secrets.HOST_IP }}
          HOST_USER: ${{ secrets.HOST_USER }}
        run: |
          scp -i ${{ secrets.SSH_KEY }} -o StrictHostKeyChecking=no -r ./apps/gui/dist/* ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }}:/var/www/html/${{ env.VERSION }}
