name: GH Release and NPM Publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'next'
    paths:
      - 'libraries/**'
      - 'internal/**'
      - 'scripts/**'
      - 'package.json'
      - '.github/workflows/publish-package.yml'
      - 'apps/gui/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: 'nostrings'
            nodeVersion: '20'
          - package: 'announce'
            nodeVersion: '20'
          - package: 'logger'
            nodeVersion: '20'
          - package: 'seed'
            nodeVersion: '20'
          - package: 'utils'
            nodeVersion: '20'
          - package: 'nwcache'
            nodeVersion: '20'
          - package: 'controlflow'
            nodeVersion: '20'
          - package: 'publisher'
            nodeVersion: '20'
          - package: 'nocap'
            nodeVersion: '20'
          - package: 'nocap-websocket-adapter-default'
            nodeVersion: '20'
          - package: 'nocap-websocket-browser-adapter-default'
            nodeVersion: '20'
          - package: 'nocap-info-adapter-default'
            nodeVersion: '20'
          - package: 'nocap-dns-adapter-default'
            nodeVersion: '20'
          - package: 'nocap-geo-adapter-default'
            nodeVersion: '20'
          - package: 'nocap-ssl-adapter-default'
            nodeVersion: '20'
          - package: 'nocap-every-adapter-default'
            nodeVersion: '20'
          - package: 'gui'
            nodeVersion: '20'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build All Packages
        run: pnpm -r run build

      # Deploy GUI steps only if the current matrix package is 'gui'
      - name: Install jq
        if: matrix.package == 'gui'
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get package version (GUI)
        if: matrix.package == 'gui'
        id: get_version
        run: |
          VERSION=$(jq -r '.version' ./apps/gui/package.json)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Prepare Directories (GUI)
        if: matrix.package == 'gui'
        run: |
          VERSION=${{ env.VERSION }}
          echo "Deploying version $VERSION"
          ssh -i ${{ secrets.GUI_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.GUI_HOST_USER }}@${{ secrets.GUI_HOST_IP }} << EOF
          set -e
          mkdir -p /var/www/${VERSION}
          rm -rf /var/www/html/
          ln -s /var/www/${VERSION} /var/www/html
          EOF

      - name: Upload Build (GUI)
        if: matrix.package == 'gui'
        run: |
          scp -i ${{ secrets.GUI_SSH_KEY }} -o StrictHostKeyChecking=no -r ./apps/gui/dist/* ${{ secrets.GUI_HOST_USER }}@${{ secrets.GUI_HOST_IP }}:/var/www/html/${{ env.VERSION }}

      - name: Find Package
        id: find_package
        run: |
          # Include apps directory as well, since we now have 'gui' there
          PKG_PATH=$(find libraries -type d -name "${{ matrix.package }}" -print -quit)
          if [ -z "$PKG_PATH" ]; then
            PKG_PATH=$(find internal -type d -name "${{ matrix.package }}" -print -quit)
          fi
          if [ -z "$PKG_PATH" ]; then
            PKG_PATH=$(find apps -type d -name "${{ matrix.package }}" -print -quit)
          fi
          echo "the_path=$PKG_PATH" >> "$GITHUB_OUTPUT"

      - name: Publish Package
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ${{ steps.find_package.outputs.the_path }}/package.json
          strategy: all
          access: public

      - name: Set Meta
        id: meta
        run: |
          RELEASE_SLUG="${{ matrix.package }}@v${{ steps.publish.outputs.version }}"
          echo "release_slug=$RELEASE_SLUG" >> "$GITHUB_OUTPUT"

      - name: Check for Tag
        id: slug_exists
        run: |
          git fetch --tags
          TAG="${{ steps.meta.outputs.release_slug }}"
          if git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
            echo "release_slug_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "release_slug_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Archive Subdirectory
        if: steps.slug_exists.outputs.release_slug_exists != 'true'
        id: archive
        run: |
          zip -r "${{ steps.meta.outputs.release_slug }}.zip" "${{ steps.find_package.outputs.the_path }}"

      - name: Create Release ${{ steps.meta.outputs.release_slug }}
        if: steps.publish.outputs.type != 'none' && steps.publish.outputs.dry_run != 'true' && steps.slug_exists.outputs.release_slug_exists != 'true'
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.meta.outputs.release_slug }}
          release_name: ${{ steps.meta.outputs.release_slug }}
          body: ""
          draft: false
          prerelease: true

      - name: Upload Release Asset ${{ steps.meta.outputs.release_slug }}.zip
        if: steps.slug_exists.outputs.release_slug_exists != 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.meta.outputs.release_slug }}.zip
          asset_name: ${{ steps.meta.outputs.release_slug }}.zip
          asset_content_type: application/zip
